# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180217_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hos_reg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hos_dir_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hos_reg_date', models.DateField(blank=True, null=True)),
                ('ambulance_count', models.IntegerField(blank=True)),
                ('hospital_mobile', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
