# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180220_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='count_of_persons_injured',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('progress', 'Progress'), ('completed', 'Completed')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='severity',
            field=models.CharField(blank=True, choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], max_length=255, null=True),
        ),
    ]
