# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180311_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ambulance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hos_dir_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hos_reg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hos_reg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HospitalProfile',
        ),
    ]
