# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-29 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180315_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='reason',
        ),
    ]
