# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-30 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180330_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='mobile',
            field=models.BigIntegerField(default=0),
        ),
    ]
