# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-29 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_userrequest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='user',
        ),
    ]
