# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180330_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='location',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
