# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 02:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180406_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
